name: aura_pet
description: Aura-Pet - Your AI Health Companion
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  google_fonts: ^4.0.0  # 用于载入 Poppins 和 Inter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/aura_quotes.json  # 100句语料库位置
